1. Import libraries

In [3]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import scipy

In [4]:
df = pd.read_csv(r'C:\Users\heidi\OneDrive\CareerFoundry\Achievement6 Sourcing Open Data\Evolution of UFC 2021-08-20\02 Data\Prepared data\ufc-master-clean1.csv', index_col = False)

In [5]:
df_mma = pd.read_csv(r'C:\Users\heidi\OneDrive\CareerFoundry\Achievement6 Sourcing Open Data\Evolution of UFC 2021-08-20\02 Data\Prepared data\pro-mma_fights.csv', index_col = False)

In [6]:
path = r'C:\Users\heidi\OneDrive\CareerFoundry\Achievement6 Sourcing Open Data\Evolution of UFC 2021-08-20\02 Data'

In [7]:
df.head()

,R_fighter,B_fighter,R_odds,B_odds,date,City,State/Province,country,Winner,title_bout,...,R_age,B_age,height_dif,reach_dif,age_dif,Finish2,finish,finish_details,finish_round,finish_round_time
0,Anthony Pettis,Alex Morono,-210,175,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,33,30,2.54,0.00,-3,U-DEC,U-DEC,NaN,3,5:00
1,Christos Giagos,Carlton Minus,-345,285,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,30,27,0.00,10.16,-3,U-DEC,U-DEC,NaN,3,5:00
2,Deron Winn,Antonio Arroyo,160,-185,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,31,31,22.86,7.62,0,U-DEC,U-DEC,NaN,3,5:00
3,Gillian Robertson,Taila Santos,-145,125,2020-12-19,Las Vegas,Nevada,USA,Blue,False,...,27,25,-2.54,-12.70,-2,U-DEC,U-DEC,NaN,3,5:00
4,Jimmy Flick,Cody Durden,-157,137,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,30,29,0.00,-2.54,-1,SUB,SUB,Triangle choke,1,3:18

In [8]:
df.shape

(4515, 31)

In [9]:
#Check for missing values
df.isnull().sum()
# The outstanding values in 'finish details' are N/A. These outstanding values refere to 'decision outcome' fights, which do not have any finish details.
# The missing values in state/province are because not all cities have states or provinces.

R_fighter               0
B_fighter               0
R_odds                  0
B_odds                  0
date                    0
City                    0
State/Province          0
country                 0
Winner                  0
title_bout              0
weight_class            0
gender                  0
no_of_rounds            0
B_Stance                0
B_Height_cms            0
B_Reach_cms             0
B_Weight_lbs            0
R_Stance                0
R_Height_cms            0
R_Reach_cms             0
R_Weight_lbs            0
R_age                   0
B_age                   0
height_dif              0
reach_dif               0
age_dif                 0
Finish2                 0
finish                  0
finish_details       2229
finish_round            0
finish_round_time       0
dtype: int64

In [10]:
df.dtypes

R_fighter             object
B_fighter             object
R_odds                 int64
B_odds                 int64
date                  object
City                  object
State/Province        object
country               object
Winner                object
title_bout              bool
weight_class          object
gender                object
no_of_rounds           int64
B_Stance              object
B_Height_cms         float64
B_Reach_cms          float64
B_Weight_lbs           int64
R_Stance              object
R_Height_cms         float64
R_Reach_cms          float64
R_Weight_lbs           int64
R_age                  int64
B_age                  int64
height_dif           float64
reach_dif            float64
age_dif                int64
Finish2               object
finish                object
finish_details        object
finish_round           int64
finish_round_time     object
dtype: object

In [11]:
# Changed dtype of 'finish_round' to integer.
df['finish_round']=df['finish_round'].fillna(0).astype(int)
df.dtypes

R_fighter             object
B_fighter             object
R_odds                 int64
B_odds                 int64
date                  object
City                  object
State/Province        object
country               object
Winner                object
title_bout              bool
weight_class          object
gender                object
no_of_rounds           int64
B_Stance              object
B_Height_cms         float64
B_Reach_cms          float64
B_Weight_lbs           int64
R_Stance              object
R_Height_cms         float64
R_Reach_cms          float64
R_Weight_lbs           int64
R_age                  int64
B_age                  int64
height_dif           float64
reach_dif            float64
age_dif                int64
Finish2               object
finish                object
finish_details        object
finish_round           int32
finish_round_time     object
dtype: object

In [12]:
# Format date to date time objects
df['date'] = pd.to_datetime(df['date'], format = '%Y-%m-%d')

In [13]:
df['date']

0      2020-12-19
1      2020-12-19
2      2020-12-19
3      2020-12-19
4      2020-12-19
          ...
4510   2010-03-21
4511   2010-03-21
4512   2010-03-21
4513   2010-03-21
4514   2010-03-21
Name: date, Length: 4515, dtype: datetime64[ns]

In [14]:
# New column extracting year from date object
df['year'] = pd.DatetimeIndex(df['date']).year
df['year']

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
4510    2010
4511    2010
4512    2010
4513    2010
4514    2010
Name: year, Length: 4515, dtype: int64

In [15]:
# Check new 'year' column
df.head()

,R_fighter,B_fighter,R_odds,B_odds,date,City,State/Province,country,Winner,title_bout,...,B_age,height_dif,reach_dif,age_dif,Finish2,finish,finish_details,finish_round,finish_round_time,year
0,Anthony Pettis,Alex Morono,-210,175,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,30,2.54,0.00,-3,U-DEC,U-DEC,NaN,3,5:00,2020
1,Christos Giagos,Carlton Minus,-345,285,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,27,0.00,10.16,-3,U-DEC,U-DEC,NaN,3,5:00,2020
2,Deron Winn,Antonio Arroyo,160,-185,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,31,22.86,7.62,0,U-DEC,U-DEC,NaN,3,5:00,2020
3,Gillian Robertson,Taila Santos,-145,125,2020-12-19,Las Vegas,Nevada,USA,Blue,False,...,25,-2.54,-12.70,-2,U-DEC,U-DEC,NaN,3,5:00,2020
4,Jimmy Flick,Cody Durden,-157,137,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,29,0.00,-2.54,-1,SUB,SUB,Triangle choke,1,3:18,2020

In [16]:
# Remove decimals (used this option instead of 'round' -option, as the latter still gave 1 decimal).
pd.set_option('precision', 1)
df

,R_fighter,B_fighter,R_odds,B_odds,date,City,State/Province,country,Winner,title_bout,...,B_age,height_dif,reach_dif,age_dif,Finish2,finish,finish_details,finish_round,finish_round_time,year
0,Anthony Pettis,Alex Morono,-210,175,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,30,2.5,0.0,-3,U-DEC,U-DEC,NaN,3,5:00,2020
1,Christos Giagos,Carlton Minus,-345,285,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,27,0.0,10.2,-3,U-DEC,U-DEC,NaN,3,5:00,2020
2,Deron Winn,Antonio Arroyo,160,-185,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,31,22.9,7.6,0,U-DEC,U-DEC,NaN,3,5:00,2020
3,Gillian Robertson,Taila Santos,-145,125,2020-12-19,Las Vegas,Nevada,USA,Blue,False,...,25,-2.5,-12.7,-2,U-DEC,U-DEC,NaN,3,5:00,2020
4,Jimmy Flick,Cody Durden,-157,137,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,29,0.0,-2.5,-1,SUB,SUB,Triangle choke,1,3:18,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,Eliot Marshall,Vladimir Matyushenko,145,-165,2010-03-21,Broomfield,Colorado,USA,Blue,False,...,39,-5.1,-7.6,-10,S-DEC,S-DEC,NaN,3,5:00,2010
4511,Eric Schafer,Jason Brilz,140,-160,2010-03-21,Broomfield,Colorado,USA,Blue,False,...,34,-10.2,-10.2,-2,U-DEC,U-DEC,NaN,3,5:00,2010
4512,John Howard,Daniel Roberts,-210,175,2010-03-21,Broomfield,Colorado,USA,Red,False,...,29,7.6,7.6,-2,KO/TKO,KO/TKO,Punches,1,2:01,2010
4513,Junior Dos Santos,Gabriel Gonzaga,-250,230,2010-03-21,Broomfield,Colorado,USA,Red,False,...,30,-5.1,-2.5,-4,KO/TKO,KO/TKO,Punches,1,3:53,2010
4514,Mike Pierce,Julio Paulino,-420,335,2010-03-21,Broomfield,Colorado,USA,Red,False,...,34,10.2,7.6,-5,U-DEC,U-DEC,NaN,3,5:00,2010

In [17]:
df.columns

Index(['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'date', 'City',
       'State/Province', 'country', 'Winner', 'title_bout', 'weight_class',
       'gender', 'no_of_rounds', 'B_Stance', 'B_Height_cms', 'B_Reach_cms',
       'B_Weight_lbs', 'R_Stance', 'R_Height_cms', 'R_Reach_cms',
       'R_Weight_lbs', 'R_age', 'B_age', 'height_dif', 'reach_dif', 'age_dif',
       'Finish2', 'finish', 'finish_details', 'finish_round',
       'finish_round_time', 'year'],
      dtype='object')

In [18]:
# Find duplicates
df_dups = df[df.duplicated()]

In [19]:
# No duplicates
df_dups.shape

(0, 32)

In [20]:
# Mixed-type columns
for col in df.columns.tolist():
      weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df[weird]) > 0:
        print (col)

finish_details

In [34]:
# Add calculated column indicating 'average_height'
df["average_height"] = (df["B_Height_cms"] + df["R_Height_cms"])/2
df["average_age"] = df['R_age'] +  df['B_age']/2
df["average_reach"] = df['B_Reach_cms'] +  df['R_Reach_cms']/2
df["average_weight"] = df['B_Weight_lbs'] +  df['R_Weight_lbs']/2
df.head()

,R_fighter,B_fighter,R_odds,B_odds,date,City,State/Province,country,Winner,title_bout,...,Finish2,finish,finish_details,finish_round,finish_round_time,year,average_height,average_age,average_reach,average_weight
0,Anthony Pettis,Alex Morono,-210,175,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,U-DEC,U-DEC,NaN,3,5:00,2020,179.1,48.0,274.3,247.5
1,Christos Giagos,Carlton Minus,-345,285,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,U-DEC,U-DEC,NaN,3,5:00,2020,177.8,43.5,280.7,247.5
2,Deron Winn,Antonio Arroyo,160,-185,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,U-DEC,U-DEC,NaN,3,5:00,2020,179.1,46.5,274.3,277.5
3,Gillian Robertson,Taila Santos,-145,125,2020-12-19,Las Vegas,Nevada,USA,Blue,False,...,U-DEC,U-DEC,NaN,3,5:00,2020,166.4,39.5,246.4,187.5
4,Jimmy Flick,Cody Durden,-157,137,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,SUB,SUB,Triangle choke,1,3:18,2020,170.2,44.5,256.5,187.5

In [35]:
df.describe()

,R_odds,B_odds,no_of_rounds,B_Height_cms,B_Reach_cms,B_Weight_lbs,R_Height_cms,R_Reach_cms,R_Weight_lbs,R_age,B_age,height_dif,reach_dif,age_dif,finish_round,year,average_height,average_age,average_reach,average_weight
count,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4.5e+03,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0,4515.0
mean,-119.6,68.3,3.2,178.2,182.5,165.0,178.1,182.6,165.5,30.0,29.5,5.8e-02,-0.2,0.4,2.4,2015.6,178.1,44.7,273.8,247.8
std,271.5,250.3,0.6,8.9,10.9,34.2,9.0,10.8,34.4,4.1,4.0,7.0e+00,9.5,5.1,1.0,2.9,8.3,4.9,15.1,50.9
min,-1700.0,-1200.0,3.0,152.4,0.0,115.0,152.4,152.4,115.0,19.0,19.0,-1.9e+02,-188.0,-16.0,1.0,2010.0,153.7,30.0,94.0,172.5
25%,-260.0,-145.0,3.0,172.7,175.3,145.0,172.7,175.3,145.0,27.0,27.0,-5.1e+00,-5.1,-3.0,1.0,2013.0,171.4,41.5,264.2,212.5
50%,-150.0,130.0,3.0,177.8,182.9,155.0,177.8,182.9,155.0,30.0,29.0,0.0e+00,0.0,0.0,3.0,2016.0,179.1,44.5,274.3,232.5
75%,128.0,225.0,3.0,185.4,190.5,185.0,185.4,190.5,185.0,33.0,32.0,5.1e+00,5.1,4.0,3.0,2018.0,184.2,48.0,284.5,277.5
max,775.0,1300.0,5.0,210.8,213.4,265.0,210.8,214.6,265.0,47.0,47.0,3.0e+01,30.5,17.0,5.0,2020.0,205.7,68.0,315.0,397.5

In [36]:
# Check data of pro_mma
df_mma.head()

,event_title,date,location,match_nr,fighter1_name,fighter2_name,win_method,win_details,round,time,year
0,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",13,Ciryl Gane,Derrick Lewis,TKO,Punches,3,4:11,2021
1,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",12,Jose Aldo,Pedro Munhoz,Decision,Unanimous,3,5:00,2021
2,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",11,Vicente Luque,Michael Chiesa,Submission,Brabo Choke,1,3:25,2021
3,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",10,Tecia Torres,Angela Hill,Decision,Unanimous,3,5:00,2021
4,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",9,Yadong Song,Casey Kenney,Decision,Split,3,5:00,2021

In [37]:
df_mma.shape

(6212, 11)

In [38]:
df_mma.dtypes

event_title              object
date             datetime64[ns]
location                 object
match_nr                  int64
fighter1_name            object
fighter2_name            object
win_method               object
win_details              object
round                     int64
time                     object
year                      int64
dtype: object

In [39]:
# Format date to date time objects
df_mma['date'] = pd.to_datetime(df_mma['date'])

In [40]:
df_mma.dtypes

event_title              object
date             datetime64[ns]
location                 object
match_nr                  int64
fighter1_name            object
fighter2_name            object
win_method               object
win_details              object
round                     int64
time                     object
year                      int64
dtype: object

In [41]:
# Check for duplicates
df_mma.isnull().sum()

event_title      0
date             0
location         0
match_nr         0
fighter1_name    0
fighter2_name    0
win_method       0
win_details      0
round            0
time             0
year             0
dtype: int64

In [42]:
# Check for duplicates
df_mma.duplicated().sum()

0

In [43]:
# Extract 'year' from date
df_mma['year'] = pd.DatetimeIndex(df_mma['date']).year
df_mma['year']

0       2021
1       2021
2       2021
3       2021
4       2021
        ...
6207    1993
6208    1993
6209    1993
6210    1993
6211    1993
Name: year, Length: 6212, dtype: int64

In [44]:
# Check added 'year' column
df_mma.head()

,event_title,date,location,match_nr,fighter1_name,fighter2_name,win_method,win_details,round,time,year
0,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",13,Ciryl Gane,Derrick Lewis,TKO,Punches,3,4:11,2021
1,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",12,Jose Aldo,Pedro Munhoz,Decision,Unanimous,3,5:00,2021
2,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",11,Vicente Luque,Michael Chiesa,Submission,Brabo Choke,1,3:25,2021
3,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",10,Tecia Torres,Angela Hill,Decision,Unanimous,3,5:00,2021
4,UFC 265 - Lewis vs. Gane,2021-08-07,"Toyota Center, Houston, Texas, United States",9,Yadong Song,Casey Kenney,Decision,Split,3,5:00,2021

In [45]:
# Remove 2021 from year column
df_mma[df_mma ['year'] < 2021]

,event_title,date,location,match_nr,fighter1_name,fighter2_name,win_method,win_details,round,time,year
314,UFC Fight Night 183 - Thompson vs. Neal,2020-12-19,"UFC Apex, Las Vegas, Nevada, United States",12,Stephen Thompson,Geoff Neal,Decision,Unanimous,5,5:00,2020
315,UFC Fight Night 183 - Thompson vs. Neal,2020-12-19,"UFC Apex, Las Vegas, Nevada, United States",11,Jose Aldo,Marlon Vera,Decision,Unanimous,3,5:00,2020
316,UFC Fight Night 183 - Thompson vs. Neal,2020-12-19,"UFC Apex, Las Vegas, Nevada, United States",10,Michel Pereira,Kalinn Williams,Decision,Unanimous,3,5:00,2020
317,UFC Fight Night 183 - Thompson vs. Neal,2020-12-19,"UFC Apex, Las Vegas, Nevada, United States",9,Rob Font,Marlon Moraes,TKO,Elbow and Punches,1,3:47,2020
318,UFC Fight Night 183 - Thompson vs. Neal,2020-12-19,"UFC Apex, Las Vegas, Nevada, United States",8,Marcin Tybura,Greg Hardy,TKO,Punches,2,4:31,2020
...,...,...,...,...,...,...,...,...,...,...,...
6207,UFC 1 - The Beginning,1993-11-12,"McNichols Arena, Denver, Colorado, United States",5,Gerard Gordeau,Kevin Rosier,TKO,Corner Stoppage,1,0:59,1993
6208,UFC 1 - The Beginning,1993-11-12,"McNichols Arena, Denver, Colorado, United States",4,Ken Shamrock,Patrick Smith,Submission,Heel Hook,1,1:49,1993
6209,UFC 1 - The Beginning,1993-11-12,"McNichols Arena, Denver, Colorado, United States",3,Royce Gracie,Art Jimmerson,Submission,Smother Choke,1,2:18,1993
6210,UFC 1 - The Beginning,1993-11-12,"McNichols Arena, Denver, Colorado, United States",2,Kevin Rosier,Zane Frazier,TKO,Punches,1,4:20,1993
6211,UFC 1 - The Beginning,1993-11-12,"McNichols Arena, Denver, Colorado, United States",1,Gerard Gordeau,Teila Tuli,TKO,Head Kick,1,0:26,1993

In [46]:
df_mma.describe()

       match_nr   round    year
count    6212.0  6212.0  6212.0
mean        6.1     2.3  2013.6
std         3.3     1.0     5.7
min         1.0     1.0  1993.0
25%         3.0     1.0  2011.0
50%         6.0     3.0  2015.0
75%         9.0     3.0  2018.0
max        15.0     5.0  2021.0

In [47]:
df_mma = df_mma.drop(columns = ['event_title', 'location', 'match_nr'])

In [323]:
df_mma.head()

,date,fighter1_name,fighter2_name,win_method,win_details,round,time,year
0,2021-08-07,Ciryl Gane,Derrick Lewis,TKO,Punches,3,4:11,2021
1,2021-08-07,Jose Aldo,Pedro Munhoz,Decision,Unanimous,3,5:00,2021
2,2021-08-07,Vicente Luque,Michael Chiesa,Submission,Brabo Choke,1,3:25,2021
3,2021-08-07,Tecia Torres,Angela Hill,Decision,Unanimous,3,5:00,2021
4,2021-08-07,Yadong Song,Casey Kenney,Decision,Split,3,5:00,2021

In [324]:
df = df[df['Finish2'] != '0']

In [325]:
df.isnull().sum()

R_fighter               0
B_fighter               0
R_odds                  0
B_odds                  0
date                    0
City                    0
State/Province        472
country                 0
Winner                  0
title_bout              0
weight_class            0
gender                  0
no_of_rounds            0
B_Stance                0
B_Height_cms            0
B_Reach_cms             0
B_Weight_lbs            0
R_Stance                0
R_Height_cms            0
R_Reach_cms             0
R_Weight_lbs            0
R_age                   0
B_age                   0
height_dif              0
reach_dif               0
age_dif                 0
Finish2                 0
finish                  0
finish_details       2229
finish_round            0
finish_round_time       0
year                    0
average_height          0
average_age             0
dtype: int64

In [326]:
df.head()

,R_fighter,B_fighter,R_odds,B_odds,date,City,State/Province,country,Winner,title_bout,...,reach_dif,age_dif,Finish2,finish,finish_details,finish_round,finish_round_time,year,average_height,average_age
0,Anthony Pettis,Alex Morono,-210,175,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,0.0,-3,U-DEC,U-DEC,NaN,3,5:00,2020,179.1,31.5
1,Christos Giagos,Carlton Minus,-345,285,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,10.2,-3,U-DEC,U-DEC,NaN,3,5:00,2020,177.8,28.5
2,Deron Winn,Antonio Arroyo,160,-185,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,7.6,0,U-DEC,U-DEC,NaN,3,5:00,2020,179.1,31.0
3,Gillian Robertson,Taila Santos,-145,125,2020-12-19,Las Vegas,Nevada,USA,Blue,False,...,-12.7,-2,U-DEC,U-DEC,NaN,3,5:00,2020,166.4,26.0
4,Jimmy Flick,Cody Durden,-157,137,2020-12-19,Las Vegas,Nevada,USA,Red,False,...,-2.5,-1,SUB,SUB,Triangle choke,1,3:18,2020,170.2,29.5